### ISSUE TITLE
Documenation does not discuss or contain examples for how templated files are found by composer.

### ISSUE THREAD

**Issue by Arripis** [ByteSquid/composer-rust#28]
After templating a jinja2 file for some configuration files I realised that I wasn't sure how to specify to composer what files i wanted to template. I realised that its recursively searching for any jinja files afterwards but this is undocumented.

**Comment by sam-bytesquid** [comment]
Thanks, will look into this.

**Comment by sam-bytesquid** [comment]
This has now been updated as of version `v2.2.0`.
